nameOverride: learning

image:
  repository: ghcr.io/sellevate/learning-service
  tag: latest

env:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  Kafka__BootstrapServers: kafka:9092
  Logging__Loki__Url: http://loki:3100

envFromConfigMap: learning-config
envFromSecret: learning-secrets

service:
  type: ClusterIP
  port: 80
