// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sellevate.Ai.Infrastructure.Data;

#nullable disable

namespace Sellevate.Ai.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AiDbContext))]
    [Migration("20260818043308_AddOrganizationQuotas")]
    partial class AddOrganizationQuotas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sellevate.Ai.Features.Dialog.Models.DialogBundle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("IconEmoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("SortOrder");

                    b.HasIndex("OrganizationId", "SortOrder");

                    b.ToTable("DialogBundles", (string)null);
                });

            modelBuilder.Entity("Sellevate.Ai.Features.Dialog.Models.DialogMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("BundleId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChatSystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FeedbackSystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentModeId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("VoiceEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("VoiceId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BundleId");

                    b.HasIndex("ParentModeId");

                    b.HasIndex("BundleId", "Key")
                        .IsUnique()
                        .HasDatabaseName("IX_DialogModes_BundleId_Key_Global")
                        .HasFilter("\"OrganizationId\" IS NULL");

                    b.HasIndex("OrganizationId", "BundleId", "Key")
                        .IsUnique()
                        .HasFilter("\"OrganizationId\" IS NOT NULL");

                    b.ToTable("DialogModes", (string)null);
                });

            modelBuilder.Entity("Sellevate.Ai.Features.Organizations.OrganizationProfileReplica", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("BannedClaimsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]");

                    b.Property<string>("GlossaryJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<string>("Icp")
                        .HasColumnType("text");

                    b.Property<string>("ObjectionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]");

                    b.Property<string>("Product")
                        .HasColumnType("text");

                    b.Property<string>("ScriptJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]");

                    b.Property<string>("Tone")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganizationId");

                    b.ToTable("OrganizationProfileReplicas", (string)null);
                });

            modelBuilder.Entity("Sellevate.Ai.Features.Quotas.Models.AiUsageRecord", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PeriodKey")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("CallCount")
                        .HasColumnType("bigint");

                    b.Property<long>("CompletionTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("EstimatedCallCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("PromptTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("SpeechCharacters")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganizationId", "PeriodKey", "Model");

                    b.ToTable("AiUsageRecords", (string)null);
                });

            modelBuilder.Entity("Sellevate.Ai.Features.Quotas.Models.OrganizationQuota", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("BatchReservePercent")
                        .HasColumnType("integer");

                    b.Property<long?>("LlmMonthlyTokenLimit")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VoiceDailyLimitMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("VoiceMonthlyLimitMinutes")
                        .HasColumnType("integer");

                    b.HasKey("OrganizationId");

                    b.ToTable("OrganizationQuotas", (string)null);
                });

            modelBuilder.Entity("Sellevate.Ai.Identity.UserReplica", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarKey")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserReplicas", (string)null);
                });

            modelBuilder.Entity("Sellevate.Ai.Features.Dialog.Models.DialogMode", b =>
                {
                    b.HasOne("Sellevate.Ai.Features.Dialog.Models.DialogBundle", "Bundle")
                        .WithMany("Modes")
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sellevate.Ai.Features.Dialog.Models.DialogMode", null)
                        .WithMany()
                        .HasForeignKey("ParentModeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bundle");
                });

            modelBuilder.Entity("Sellevate.Ai.Features.Dialog.Models.DialogBundle", b =>
                {
                    b.Navigation("Modes");
                });
#pragma warning restore 612, 618
        }
    }
}
