// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sellevate.Gamification.Infrastructure.Data;

#nullable disable

namespace Sellevate.Gamification.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GamificationDbContext))]
    partial class GamificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sellevate.BuildingBlocks.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DispatchedAt");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Sellevate.Gamification.Features.Achievements.Models.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConditionThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Achievements", (string)null);
                });

            modelBuilder.Entity("Sellevate.Gamification.Features.Achievements.Models.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserAchievements", (string)null);
                });

            modelBuilder.Entity("Sellevate.Gamification.Features.Achievements.Models.UserLearningProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletedLessonCount")
                        .HasColumnType("integer");

                    b.Property<bool>("HasCompletedAnySkill")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserLearningProgress", (string)null);
                });

            modelBuilder.Entity("Sellevate.Gamification.Features.Gamification.Models.ExerciseTypeReward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseXpReward")
                        .HasColumnType("integer");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseType")
                        .IsUnique();

                    b.ToTable("ExerciseTypeRewards", (string)null);
                });

            modelBuilder.Entity("Sellevate.Gamification.Features.Gamification.Models.GamificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DailyXpGoal")
                        .HasColumnType("integer");

                    b.Property<int>("DialogWeightConfidence")
                        .HasColumnType("integer");

                    b.Property<int>("DialogWeightGoal")
                        .HasColumnType("integer");

                    b.Property<int>("DialogWeightObjection")
                        .HasColumnType("integer");

                    b.Property<int>("DialogWeightStructure")
                        .HasColumnType("integer");

                    b.Property<double>("DialogXpMultiplier")
                        .HasColumnType("double precision");

                    b.Property<int>("WeeklyXpGoal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GamificationSettings", (string)null);
                });

            modelBuilder.Entity("Sellevate.Gamification.Features.Gamification.Models.StreakMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayCount")
                        .HasColumnType("integer");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DayCount")
                        .IsUnique();

                    b.ToTable("StreakMilestones", (string)null);
                });

            modelBuilder.Entity("Sellevate.Gamification.Features.Gamification.Models.UserExperiencePointsRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceEventId")
                        .IsUnique()
                        .HasFilter("\"SourceEventId\" IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("UserXpRecords", (string)null);
                });

            modelBuilder.Entity("Sellevate.Gamification.Features.Gamification.Models.UserStreak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStreakDayCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("LastActivityDate")
                        .HasColumnType("date");

                    b.Property<int>("LongestStreakDayCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStreaks", (string)null);
                });

            modelBuilder.Entity("Sellevate.Gamification.Features.League.Models.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("WeekEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("WeekStartDate", "Tier")
                        .IsUnique();

                    b.ToTable("Leagues", (string)null);
                });

            modelBuilder.Entity("Sellevate.Gamification.Features.League.Models.LeagueMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("PromotionOutcome")
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeeklyXpAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("UserId", "LeagueId")
                        .IsUnique();

                    b.ToTable("LeagueMemberships", (string)null);
                });

            modelBuilder.Entity("Sellevate.Gamification.Features.League.Models.LeagueSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CurrentPeriodEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("CurrentPeriodStartDate")
                        .HasColumnType("date");

                    b.Property<int>("DemotionZoneSize")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumLeagueParticipantCount")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodLengthDays")
                        .HasColumnType("integer");

                    b.Property<int>("PromotionZoneSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LeagueSettings", (string)null);
                });

            modelBuilder.Entity("Sellevate.Gamification.Features.League.Models.LeagueTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("LeagueTiers", (string)null);
                });

            modelBuilder.Entity("Sellevate.Gamification.Identity.UserReplica", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarKey")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserReplicas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
