using Microsoft.EntityFrameworkCore;
using Sellevate.Learning.Features.Content;
using Sellevate.Learning.Features.ContentAdaptation.Models;
using Sellevate.Learning.Infrastructure.Data;

namespace Sellevate.Learning.Features.ContentAdaptation.Services.Implementation;

/// <summary>
/// Phase 40.32. What «все упражнения этапа "закрытие"» actually resolves to.
///
/// <para>
/// <b>The scope is read through 40.18's override resolution, and that single decision answers three
/// questions at once.</b> An organization that has already forked a lesson gets <i>their</i>
/// exercises in the batch, not the global originals — so a rewrite is proposed against the wording
/// their team actually sees, and accepting it edits the copy they already own. An organization that
/// has not forked gets the global library rows, and accepting a proposal forks the lesson at that
/// moment, which is what copy-on-write means. And neither case can produce both, because resolution
/// is precisely the rule that hides a base row when a live override of it exists — without it a
/// forked lesson would appear in the batch twice and a reviewer would be asked the same question
/// about two rows, one of which nobody reads.
/// </para>
///
/// <para>
/// <b>Archived lessons are out of scope</b>, and that falls out of the same call rather than being a
/// rule of its own. It is the right answer for money: a lesson generated by 40.27 and never
/// un-archived is content nobody has looked at, and paying to adapt its tone before anybody has
/// decided to keep it is paying twice for the same undecided question.
/// </para>
/// </summary>
internal static class ContentAdaptationScopeCollector
{
    /// <summary>
    /// The exercises of one stage, in the order a learner meets them — lesson by lesson, and inside a
    /// lesson by position. The queue is walked in that order, so a reviewer reads a lesson's
    /// exercises the way the lesson plays them instead of in whatever order the database returned.
    /// </summary>
    public static async Task<IReadOnlyList<ContentAdaptationScopeRow>> CollectAsync(
        LearningDbContext databaseContext,
        string stageKey,
        int limit,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(databaseContext);

        var lessons = databaseContext.Lessons
            .Where(lesson => databaseContext.Topics.Any(topic =>
                topic.Id == lesson.TopicId
                && databaseContext.Skills.Any(skill => skill.Id == topic.SkillId && skill.Stage == stageKey)))
            .ResolveOverrides(databaseContext);

        // Joined rather than projected through a correlated subquery: the title is only a label, and a
        // subquery inside the projection is the kind of LINQ that compiles, reads fine, and fails on
        // the first real Postgres connection — which for a background worker is the least visible
        // place in the service.
        var rows = await databaseContext.Exercises
            .AsNoTracking()
            .Where(exercise => lessons.Any(lesson => lesson.Id == exercise.LessonId))
            .Join(
                databaseContext.Lessons,
                exercise => exercise.LessonId,
                lesson => lesson.Id,
                (exercise, lesson) => new { Exercise = exercise, lesson.Title })
            .OrderBy(row => row.Exercise.LessonId)
            .ThenBy(row => row.Exercise.OrderInLesson)
            .ThenBy(row => row.Exercise.Id)
            .Take(limit)
            .ToListAsync(cancellationToken);

        return rows
            .Select(row => new ContentAdaptationScopeRow(
                row.Exercise.Id,
                row.Exercise.LessonId,
                row.Title,
                row.Exercise.Type,
                row.Exercise.OrderInLesson,
                row.Exercise.SerializedContent,
                row.Exercise.CustomAiPrompt))
            .ToList();
    }

    /// <summary>
    /// How many exercises the stage holds, without pulling any of their bodies. Asked before a batch
    /// is created so that a stage above the ceiling is refused with the number, rather than silently
    /// truncated to the first sixty — a truncated «все упражнения этапа» is a promise the product
    /// quietly failed to keep.
    /// </summary>
    public static async Task<int> CountAsync(
        LearningDbContext databaseContext,
        string stageKey,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(databaseContext);

        var lessons = databaseContext.Lessons
            .Where(lesson => databaseContext.Topics.Any(topic =>
                topic.Id == lesson.TopicId
                && databaseContext.Skills.Any(skill => skill.Id == topic.SkillId && skill.Stage == stageKey)))
            .ResolveOverrides(databaseContext);

        return await databaseContext.Exercises
            .CountAsync(exercise => lessons.Any(lesson => lesson.Id == exercise.LessonId), cancellationToken);
    }
}
