#!/usr/bin/env python3
"""Enforces the SalesTrainer CODESTYLE rules that dotnet format cannot check.

Rule 9 — comments are forbidden entirely (no // line comments, no /* */ block
comments, no /// XML doc prose). Rule 1 — a curated set of forbidden
abbreviations may not appear as standalone identifiers.

Scope is passed as command-line paths (defaults to the identity service). Files
under obj/, bin/, Migrations/, and generated files (*.g.cs, *.Designer.cs,
GlobalUsings, AssemblyInfo, anything marked <auto-generated>) are skipped.
"""
import pathlib
import re
import sys

FORBIDDEN_ABBREVIATIONS = {
    "ctx", "req", "res", "msg", "cfg", "repo", "impl", "svc", "mgr", "cmd",
    "conn", "dest", "prop", "attr", "elem", "idx", "len", "btn", "pwd", "addr",
    "usr", "num", "val", "err", "temp", "info", "util", "db", "ctxt",
    "ex", "ext",
}

IDENTIFIER_PATTERN = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")

SKIP_NAME_MARKERS = (".g.cs", ".designer.cs", "globalusings", "assemblyinfo")


def is_skipped(path: pathlib.Path) -> bool:
    lowered = path.name.lower()
    if any(marker in lowered for marker in SKIP_NAME_MARKERS):
        return True
    parts = {part.lower() for part in path.parts}
    return bool(parts & {"obj", "bin", "migrations"})


def strip_strings_and_find_comment(line: str):
    """Returns (comment_column, code_without_strings_or_comments).

    Walks the line tracking string/char literals so a // inside a string or a
    URL is not mistaken for a comment. comment_column is the index of the first
    real comment marker, or None.
    """
    index = 0
    length = len(line)
    code_characters = []
    in_string = False
    in_char = False
    in_verbatim = False
    while index < length:
        character = line[index]
        following = line[index + 1] if index + 1 < length else ""
        if in_string:
            if in_verbatim:
                if character == '"' and following == '"':
                    index += 2
                    continue
                if character == '"':
                    in_string = False
                    in_verbatim = False
            else:
                if character == "\\":
                    index += 2
                    continue
                if character == '"':
                    in_string = False
            index += 1
            continue
        if in_char:
            if character == "\\":
                index += 2
                continue
            if character == "'":
                in_char = False
            index += 1
            continue
        if character == '"':
            in_string = True
            in_verbatim = line[index - 1] == "@" if index > 0 else False
            index += 1
            continue
        if character == "'":
            in_char = True
            index += 1
            continue
        if character == "/" and following == "/":
            return index, "".join(code_characters)
        if character == "/" and following == "*":
            return index, "".join(code_characters)
        code_characters.append(character)
        index += 1
    return None, "".join(code_characters)


def lint_file(path: pathlib.Path):
    violations = []
    text = path.read_text(encoding="utf-8")
    if "<auto-generated" in text:
        return violations
    in_block_comment = False
    for line_number, line in enumerate(text.splitlines(), start=1):
        if in_block_comment:
            violations.append((line_number, "block comment (Rule 9)"))
            if "*/" in line:
                in_block_comment = False
            continue
        comment_column, code = strip_strings_and_find_comment(line)
        if comment_column is not None:
            marker = line[comment_column:comment_column + 2]
            violations.append((line_number, "comment forbidden (Rule 9)"))
            if marker == "/*" and "*/" not in line[comment_column:]:
                in_block_comment = True
        for match in IDENTIFIER_PATTERN.finditer(code):
            if match.group() in FORBIDDEN_ABBREVIATIONS:
                violations.append(
                    (line_number, f"forbidden abbreviation '{match.group()}' (Rule 1)"))
    return violations


def main(argv):
    roots = argv[1:] or ["src/backend/identity-service"]
    total = 0
    for root in roots:
        for path in sorted(pathlib.Path(root).rglob("*.cs")):
            if is_skipped(path):
                continue
            for line_number, reason in lint_file(path):
                print(f"{path}:{line_number}: {reason}")
                total += 1
    if total:
        print(f"\ncodestyle-lint: {total} violation(s) found.")
        return 1
    print("codestyle-lint: clean.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
