#!/usr/bin/env python3
"""Enforces the SalesTrainer CODESTYLE rules that dotnet format cannot check.

Rule 9 — `///` XML documentation is allowed (and required on service and
infrastructure classes); `//` explanatory comments and `/* */` block comments
are forbidden. Rule 1 — a curated set of forbidden abbreviations may not appear
as standalone identifiers.

Scope is passed as command-line paths (defaults to the identity service). Files
under obj/, bin/, Migrations/, and generated files (*.g.cs, *.Designer.cs,
GlobalUsings, AssemblyInfo, anything marked <auto-generated>) are skipped.
"""
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from lib_csharp_source import is_skipped, strip_strings_and_find_comment

FORBIDDEN_ABBREVIATIONS = {
    "ctx", "req", "res", "msg", "cfg", "repo", "impl", "svc", "mgr", "cmd",
    "conn", "dest", "prop", "attr", "elem", "idx", "len", "btn", "pwd", "addr",
    "usr", "num", "val", "err", "temp", "info", "util", "db", "ctxt",
    "ex", "ext",
}

IDENTIFIER_PATTERN = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def lint_file(path: pathlib.Path):
    violations = []
    text = path.read_text(encoding="utf-8")
    if "<auto-generated" in text:
        return violations
    in_block_comment = False
    for line_number, line in enumerate(text.splitlines(), start=1):
        if in_block_comment:
            violations.append((line_number, "block comment (Rule 9)"))
            if "*/" in line:
                in_block_comment = False
            continue
        comment_column, code = strip_strings_and_find_comment(line)
        if comment_column is not None:
            marker = line[comment_column:comment_column + 2]
            violations.append(
                (line_number,
                 "explanatory comment forbidden, use /// XML documentation (Rule 9)"))
            if marker == "/*" and "*/" not in line[comment_column:]:
                in_block_comment = True
        for match in IDENTIFIER_PATTERN.finditer(code):
            if match.group() in FORBIDDEN_ABBREVIATIONS:
                violations.append(
                    (line_number, f"forbidden abbreviation '{match.group()}' (Rule 1)"))
    return violations


def main(argv):
    roots = argv[1:] or ["src/backend/identity-service"]
    total = 0
    for root in roots:
        for path in sorted(pathlib.Path(root).rglob("*.cs")):
            if is_skipped(path):
                continue
            for line_number, reason in lint_file(path):
                print(f"{path}:{line_number}: {reason}")
                total += 1
    if total:
        print(f"\ncodestyle-lint: {total} violation(s) found.")
        return 1
    print("codestyle-lint: clean.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
