#!/usr/bin/env bash
# Run the frontend (Next.js) LOCALLY on the host in dev mode (hot reload),
# pointed at the locally-run backend. Reads src/frontend/.env.local.
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib-local-env.sh"

cd "$REPO_ROOT/src/frontend"

if [[ ! -f .env.local ]]; then
  echo "==> .env.local not found; generating it from the root .env..."
  load_root_env
  cat > .env.local <<EOF
# Auto-generated by scripts/dev-frontend.sh for local dev. Not committed.
NEXT_PUBLIC_API_URL=http://localhost:${LOCAL_BACKEND_PORT}
NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
LOKI_URL=http://localhost:${LOCAL_LOKI_PORT}
EOF
fi

echo "==> Frontend -> http://localhost:${LOCAL_FRONTEND_PORT} (next dev)"
exec npm run dev -- --port "${LOCAL_FRONTEND_PORT}" "$@"
