#!/usr/bin/env python3
"""Enforces the rule from docs/CODESTYLE.md ("Tenant-scoped DbContext registration") and
docs/TENANCY/TENANCY.md section 1.4: never register a DbContext with AddDbContextPool.

EF Core's context pool reuses the same pooled instance — and everything it closed over at
construction time, including the ITenantContext-backed global query filter — across unrelated
requests for different organizations. The first tenant to touch a pooled instance would silently
leak its query filter onto every later caller.

Nothing in this codebase uses AddDbContextPool today, so the cheapest safe rule is a blanket ban
rather than tracking which contexts are "tenant-scoped yet" (Phase 40.4).

Only code is scanned, never comments or string literals: CODESTYLE.md section 9 requires
`///` documentation on infrastructure classes, so this very ban is expected to appear as prose
inside the DbContext summaries it polices. Scanning raw text made every such summary a
violation.

Scope is passed as command-line paths (defaults to the whole backend). Files under obj/, bin/, and
Migrations/ are skipped.
"""
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from lib_csharp_source import is_skipped, iterate_code_lines

ADD_DB_CONTEXT_POOL_PATTERN = re.compile(r"\bAddDbContextPool\b")


def lint_file(path: pathlib.Path):
    violations = []
    text = path.read_text(encoding="utf-8")
    if "<auto-generated" in text:
        return violations

    for line_number, code in iterate_code_lines(text):
        if ADD_DB_CONTEXT_POOL_PATTERN.search(code):
            violations.append((
                line_number,
                "AddDbContextPool is forbidden — it would silently leak one tenant's query "
                "filter onto another's requests (docs/TENANCY/TENANCY.md section 1.4, "
                "docs/CODESTYLE.md). Use AddDbContext instead.",
            ))

    return violations


def main(argv):
    roots = argv[1:] or ["src/backend"]
    total = 0
    for root in roots:
        for path in sorted(pathlib.Path(root).rglob("*.cs")):
            if is_skipped(path):
                continue
            for line_number, reason in lint_file(path):
                print(f"{path}:{line_number}: {reason}")
                total += 1
    if total:
        print(f"\ntenancy-pool-lint: {total} violation(s) found.")
        return 1
    print("tenancy-pool-lint: clean.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
