#!/usr/bin/env python3
"""Enforces the multi-tenancy request boundary rule from docs/TENANCY/TENANCY.md
section 1.3: the organization is never read from the request body, query
string, or route. Only the gateway-validated X-Organization-Id header (via
Sellevate.BuildingBlocks.Identity.IdentityHeaders / ITenantContext) may supply
it.

Three checks:
  1. A request DTO (file name ending in Request.cs or Dto.cs) declaring an
     OrganizationId member — that member would be filled from the request
     body.
  2. A [FromQuery] / [FromRoute] binding named organizationId — the query
     string / route path cases.
  3. A route template containing the literal segment {organizationId}.

Scope is passed as command-line paths (defaults to the whole backend). Files
under obj/, bin/, and Migrations/ are skipped.
"""
import pathlib
import re
import sys

ORGANIZATION_ID_IDENTIFIER_PATTERN = re.compile(r"\bOrganizationId\b")
FROM_QUERY_OR_ROUTE_PATTERN = re.compile(r"\[From(?:Query|Route)\b[^\]]*\]")
ORGANIZATION_ID_BINDING_NAME_PATTERN = re.compile(r"\borganizationId\b", re.IGNORECASE)
ROUTE_TEMPLATE_ORGANIZATION_PATTERN = re.compile(r"\{organizationId\}", re.IGNORECASE)

REQUEST_DTO_FILENAME_PATTERN = re.compile(r"(Request|Dto)\.cs$")

SKIP_NAME_MARKERS = (".g.cs", ".designer.cs", "globalusings", "assemblyinfo")


def is_skipped(path: pathlib.Path) -> bool:
    lowered = path.name.lower()
    if any(marker in lowered for marker in SKIP_NAME_MARKERS):
        return True
    parts = {part.lower() for part in path.parts}
    return bool(parts & {"obj", "bin", "migrations"})


def lint_file(path: pathlib.Path):
    violations = []
    text = path.read_text(encoding="utf-8")
    if "<auto-generated" in text:
        return violations

    is_request_dto_file = bool(REQUEST_DTO_FILENAME_PATTERN.search(path.name))

    for line_number, line in enumerate(text.splitlines(), start=1):
        if is_request_dto_file and ORGANIZATION_ID_IDENTIFIER_PATTERN.search(line):
            violations.append((
                line_number,
                "organization id must never appear in a request DTO — read it only from "
                "the gateway-validated X-Organization-Id header (TENANCY.md section 1.3)",
            ))

        if FROM_QUERY_OR_ROUTE_PATTERN.search(line) and ORGANIZATION_ID_BINDING_NAME_PATTERN.search(line):
            violations.append((
                line_number,
                "organization id must never be bound from a query string or route parameter "
                "(TENANCY.md section 1.3)",
            ))

        if ROUTE_TEMPLATE_ORGANIZATION_PATTERN.search(line):
            violations.append((
                line_number,
                "route template must not carry an organization id segment "
                "(TENANCY.md section 1.3)",
            ))

    return violations


def main(argv):
    roots = argv[1:] or ["src/backend"]
    total = 0
    for root in roots:
        for path in sorted(pathlib.Path(root).rglob("*.cs")):
            if is_skipped(path):
                continue
            for line_number, reason in lint_file(path):
                print(f"{path}:{line_number}: {reason}")
                total += 1
    if total:
        print(f"\ntenancy-boundary-lint: {total} violation(s) found.")
        return 1
    print("tenancy-boundary-lint: clean.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
