namespace Sellevate.Company.Features.Companies.Models;

public sealed class Company
{
    public Guid Id { get; set; }
    public Guid UserId { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public CompanyStatus Status { get; set; } = CompanyStatus.Lead;

    /// <summary>When the next follow-up with this company is due. Null means no follow-up is scheduled.</summary>
    public DateTime? NextActionAt { get; set; }

    /// <summary>Free-form note attached to the scheduled follow-up (e.g. "call about the proposal").</summary>
    public string? NextActionNote { get; set; }

    /// <summary>
    /// When the due-follow-up reminder was published for the current <see cref="NextActionAt"/>.
    /// Null means no reminder has been sent yet for this due date. Reset to null whenever
    /// <see cref="NextActionAt"/> is rescheduled, so a rescheduled follow-up notifies again.
    /// </summary>
    public DateTime? FollowUpNotifiedAt { get; set; }

    /// <summary>Cached markdown pre-call cheat sheet ("шпаргалка") generated by ai-service. Null until first generated.</summary>
    public string? BriefingContent { get; set; }

    /// <summary>When <see cref="BriefingContent"/> was last (re)generated. Null until first generated.</summary>
    public DateTime? BriefingGeneratedAt { get; set; }

    /// <summary>
    /// Cached readiness-score JSON (score/strengths/gaps/recommendation) generated by ai-service
    /// from the company's practice-call feedback. Null until first generated, and cleared whenever
    /// a new practice call is created so the next GET regenerates it.
    /// </summary>
    public string? ReadinessJson { get; set; }

    /// <summary>When <see cref="ReadinessJson"/> was last (re)generated. Null until first generated.</summary>
    public DateTime? ReadinessGeneratedAt { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }

    public ICollection<CallLogEntry> CallLogEntries { get; set; } = new List<CallLogEntry>();
    public ICollection<PracticeCall> PracticeCalls { get; set; } = new List<PracticeCall>();
    public ICollection<CompanyContact> Contacts { get; set; } = new List<CompanyContact>();
    public ICollection<CompanyPersona> Personas { get; set; } = new List<CompanyPersona>();
}
