// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sellevate.Learning.Infrastructure.Data;

#nullable disable

namespace Sellevate.Learning.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LearningDbContext))]
    partial class LearningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sellevate.BuildingBlocks.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DispatchedAt");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Assignments.Models.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletionRule")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeadlineNoticeSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Goal")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("OpensAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RepeatOfAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("RepeatSchedule")
                        .HasColumnType("jsonb");

                    b.Property<int?>("RepeatWaveIndex")
                        .HasColumnType("integer");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("draft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CreatedAt");

                    b.HasIndex("RepeatOfAssignmentId", "RepeatWaveIndex")
                        .IsUnique()
                        .HasFilter("\"RepeatOfAssignmentId\" IS NOT NULL");

                    b.HasIndex("OrganizationId", "Status", "Deadline");

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Assignments.Models.AssignmentProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<int?>("BestScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstOpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("not_started");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId", "Status");

                    b.HasIndex("OrganizationId", "AssignmentId", "UserId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "UserId", "Status");

                    b.ToTable("AssignmentProgressRecords", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Assignments.Models.UserDialogScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DialogModeId")
                        .HasColumnType("uuid");

                    b.Property<string>("DialogModeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "UserId", "SessionId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "UserId", "DialogModeKey", "EvaluatedAt");

                    b.ToTable("UserDialogScores", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Content.Models.OrganizationProfileReplica", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("BannedClaimsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]");

                    b.Property<string>("GlossaryJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<string>("Icp")
                        .HasColumnType("text");

                    b.Property<string>("ObjectionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]");

                    b.Property<string>("Product")
                        .HasColumnType("text");

                    b.Property<string>("ScriptJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]");

                    b.Property<string>("Tone")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganizationId");

                    b.ToTable("OrganizationProfileReplicas", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.ContentAdaptation.Models.ContentAdaptationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AppliedExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("BaseContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ChangedFieldCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Findings")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("LessonTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("OrderInLesson")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProposedContent")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("OrganizationId", "ExerciseId", "Status");

                    b.HasIndex("OrganizationId", "JobId", "Status");

                    b.HasIndex("OrganizationId", "JobId", "LessonId", "OrderInLesson");

                    b.ToTable("ContentAdaptationItems", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.ContentAdaptation.Models.ContentAdaptationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("tone_rewrite");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("StageKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("preparing");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CreatedAt");

                    b.HasIndex("OrganizationId", "Mode", "StageKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ContentAdaptationJobs_Live")
                        .HasFilter("\"Status\" IN ('preparing', 'awaiting_review')");

                    b.HasIndex("OrganizationId", "Status", "CreatedAt");

                    b.ToTable("ContentAdaptationJobs", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.ContentGeneration.Models.ContentGenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GapSourceRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Insufficiency")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProducedExerciseCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProducedLessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProducedLessonVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceMaterial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("structuring");

                    b.Property<string>("Structure")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("StructuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StructuredMaterialLength")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CreatedAt");

                    b.HasIndex("OrganizationId", "GapSourceRef")
                        .HasFilter("\"GapSourceRef\" IS NOT NULL");

                    b.HasIndex("OrganizationId", "ProducedLessonId");

                    b.HasIndex("OrganizationId", "Status", "CreatedAt");

                    b.ToTable("ContentGenerationJobs", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.DailyQuotes.Models.DailyQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyQuotes", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.DialogReviews.Models.DialogReviewNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AdjustedScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DialogModeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("DisputedScore")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("coaching_note");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("QuotedFromMessageIndex")
                        .HasColumnType("integer");

                    b.Property<string>("QuotedText")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<int?>("QuotedToMessageIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Resolution")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("open");

                    b.Property<Guid>("SubjectUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "SessionId");

                    b.HasIndex("OrganizationId", "SubjectUserId", "Status");

                    b.HasIndex("OrganizationId", "Kind", "Status", "CreatedAt");

                    b.ToTable("DialogReviewNotes", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Exercises.Models.ExerciseTypePrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseType")
                        .IsUnique();

                    b.ToTable("ExerciseTypePrompts");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Lessons.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomAiPrompt")
                        .HasColumnType("text");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderInLesson")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SerializedContent")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("OrganizationId", "LessonId", "OrderInLesson");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Lessons.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("OrderInTopic")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentLessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentLessonId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Lessons_Slug_Global")
                        .HasFilter("\"OrganizationId\" IS NULL");

                    b.HasIndex("TopicId");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "TopicId", "OrderInTopic");

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Lessons.Models.LessonVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaseVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBreaking")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("draft");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaseVersionId");

                    b.HasIndex("LessonId")
                        .IsUnique()
                        .HasDatabaseName("IX_LessonVersions_LessonId_Draft")
                        .HasFilter("\"Status\" = 'draft'");

                    b.HasIndex("LessonId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "LessonId", "VersionNumber");

                    b.ToTable("LessonVersions", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Lessons.Models.UserExerciseAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LessonVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("SerializedAiFeedback")
                        .HasColumnType("jsonb");

                    b.Property<string>("SerializedAnswer")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "LessonVersionId", "ExerciseId");

                    b.HasIndex("OrganizationId", "UserId", "ExerciseId");

                    b.ToTable("UserExerciseAttempts");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Lessons.Models.UserLessonProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BestScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LessonVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "LessonVersionId");

                    b.HasIndex("OrganizationId", "UserId", "LessonId");

                    b.ToTable("UserLessonProgressRecords");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Programs.Models.ProgramEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreviousProgramVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgramVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SwitchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProgramVersionId");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.ToTable("ProgramEnrollments", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Programs.Models.ProgramItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LessonVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgramVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LessonVersionId");

                    b.HasIndex("ProgramVersionId", "LessonId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "ProgramVersionId", "OrderIndex");

                    b.ToTable("ProgramItems", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Programs.Models.ProgramVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("draft");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProgramVersions_OrganizationId_Draft")
                        .HasFilter("\"Status\" = 'draft'");

                    b.HasIndex("OrganizationId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ProgramVersions", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Reference.Models.ReferenceMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MarkdownContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentMaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentMaterialId");

                    b.HasIndex("OrganizationId", "SkillId", "SortOrder");

                    b.ToTable("ReferenceMaterials");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.SkillTree.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderInTree")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("general");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IconicName")
                        .IsUnique()
                        .HasDatabaseName("IX_Skills_IconicName_Global")
                        .HasFilter("\"OrganizationId\" IS NULL");

                    b.HasIndex("OrganizationId", "IconicName")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Stage");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.SkillTree.Models.SkillStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accent")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SkillStages");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.SkillTree.Models.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IconicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderInSkill")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IconicName")
                        .IsUnique()
                        .HasDatabaseName("IX_Topics_IconicName_Global")
                        .HasFilter("\"OrganizationId\" IS NULL");

                    b.HasIndex("SkillId");

                    b.HasIndex("OrganizationId", "IconicName")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "SkillId", "OrderInSkill");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.SkillTree.Models.UserSkillProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletedLessonCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalLessonCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "UserId", "SkillId");

                    b.ToTable("UserSkillProgressRecords");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.TeamInsights.Models.TeamSkillGapDismissal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccuracyPercentAtDismissal")
                        .HasColumnType("integer");

                    b.Property<int>("AttemptCountAtDismissal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DismissedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("StageKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "StageKey")
                        .IsUnique();

                    b.ToTable("TeamSkillGapDismissals", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Techniques.Models.Technique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CaseJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DialogJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTechniqueId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PrimarySkillId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentTechniqueId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Techniques_Slug_Global")
                        .HasFilter("\"OrganizationId\" IS NULL");

                    b.HasIndex("OrganizationId", "PrimarySkillId");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "SortOrder");

                    b.ToTable("Techniques", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Techniques.Models.TechniqueCoach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarSeed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ChallengesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TechniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TechniqueId")
                        .IsUnique();

                    b.ToTable("TechniqueCoaches", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Techniques.Models.TechniqueSkill", b =>
                {
                    b.Property<Guid>("TechniqueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("TechniqueId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("TechniqueSkills", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Techniques.Models.UserTechniqueProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastPracticedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MasteryPercent")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("PracticeCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TechniqueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "UserId");

                    b.HasIndex("OrganizationId", "UserId", "TechniqueId")
                        .IsUnique();

                    b.ToTable("UserTechniqueProgress", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Identity.UserReplica", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarKey")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserReplicas", (string)null);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Assignments.Models.Assignment", b =>
                {
                    b.HasOne("Sellevate.Learning.Features.Assignments.Models.Assignment", null)
                        .WithMany()
                        .HasForeignKey("RepeatOfAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Assignments.Models.AssignmentProgress", b =>
                {
                    b.HasOne("Sellevate.Learning.Features.Assignments.Models.Assignment", "Assignment")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.ContentAdaptation.Models.ContentAdaptationItem", b =>
                {
                    b.HasOne("Sellevate.Learning.Features.ContentAdaptation.Models.ContentAdaptationJob", "Job")
                        .WithMany("Items")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Lessons.Models.Exercise", b =>
                {
                    b.HasOne("Sellevate.Learning.Features.Lessons.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Lessons.Models.Lesson", b =>
                {
                    b.HasOne("Sellevate.Learning.Features.Lessons.Models.Lesson", "ParentLesson")
                        .WithMany()
                        .HasForeignKey("ParentLessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sellevate.Learning.Features.SkillTree.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentLesson");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Lessons.Models.LessonVersion", b =>
                {
                    b.HasOne("Sellevate.Learning.Features.Lessons.Models.LessonVersion", null)
                        .WithMany()
                        .HasForeignKey("BaseVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sellevate.Learning.Features.Lessons.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Programs.Models.ProgramEnrollment", b =>
                {
                    b.HasOne("Sellevate.Learning.Features.Programs.Models.ProgramVersion", "ProgramVersion")
                        .WithMany()
                        .HasForeignKey("ProgramVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProgramVersion");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Programs.Models.ProgramItem", b =>
                {
                    b.HasOne("Sellevate.Learning.Features.Programs.Models.ProgramVersion", "ProgramVersion")
                        .WithMany("Items")
                        .HasForeignKey("ProgramVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramVersion");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Reference.Models.ReferenceMaterial", b =>
                {
                    b.HasOne("Sellevate.Learning.Features.Reference.Models.ReferenceMaterial", null)
                        .WithMany()
                        .HasForeignKey("ParentMaterialId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.SkillTree.Models.Topic", b =>
                {
                    b.HasOne("Sellevate.Learning.Features.SkillTree.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Techniques.Models.Technique", b =>
                {
                    b.HasOne("Sellevate.Learning.Features.Techniques.Models.Technique", null)
                        .WithMany()
                        .HasForeignKey("ParentTechniqueId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Techniques.Models.TechniqueCoach", b =>
                {
                    b.HasOne("Sellevate.Learning.Features.Techniques.Models.Technique", null)
                        .WithOne("Coach")
                        .HasForeignKey("Sellevate.Learning.Features.Techniques.Models.TechniqueCoach", "TechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Techniques.Models.TechniqueSkill", b =>
                {
                    b.HasOne("Sellevate.Learning.Features.Techniques.Models.Technique", null)
                        .WithMany("AdditionalSkills")
                        .HasForeignKey("TechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Assignments.Models.Assignment", b =>
                {
                    b.Navigation("ProgressRecords");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.ContentAdaptation.Models.ContentAdaptationJob", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Programs.Models.ProgramVersion", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Sellevate.Learning.Features.Techniques.Models.Technique", b =>
                {
                    b.Navigation("AdditionalSkills");

                    b.Navigation("Coach");
                });
#pragma warning restore 612, 618
        }
    }
}
