// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sellevate.Social.Infrastructure.Data;

#nullable disable

namespace Sellevate.Social.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SocialDbContext))]
    [Migration("20260816113615_RefreshTenantPoliciesForPlatformStaff")]
    partial class RefreshTenantPoliciesForPlatformStaff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sellevate.Social.Features.Discuss.Models.DiscussPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OwnerType", "OwnerId", "OrderIndex");

                    b.ToTable("DiscussPhotos", (string)null);
                });

            modelBuilder.Entity("Sellevate.Social.Features.Discuss.Models.DiscussReply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpvoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.HasIndex("OrganizationId", "AuthorId");

                    b.HasIndex("OrganizationId", "ThreadId", "CreatedAt");

                    b.ToTable("DiscussReplies", (string)null);
                });

            modelBuilder.Entity("Sellevate.Social.Features.Discuss.Models.DiscussTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCurated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_DiscussTags_Slug_Global")
                        .HasFilter("\"OrganizationId\" IS NULL");

                    b.HasIndex("OrganizationId", "IsCurated");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique();

                    b.ToTable("DiscussTags", (string)null);
                });

            modelBuilder.Entity("Sellevate.Social.Features.Discuss.Models.DiscussThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedReplyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHot")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpvoteCount")
                        .HasColumnType("integer");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "AuthorId");

                    b.HasIndex("OrganizationId", "CreatedAt");

                    b.HasIndex("OrganizationId", "IsPinned");

                    b.HasIndex("OrganizationId", "LastActivityAt");

                    b.HasIndex("OrganizationId", "UpvoteCount");

                    b.ToTable("DiscussThreads", (string)null);
                });

            modelBuilder.Entity("Sellevate.Social.Features.Discuss.Models.DiscussThreadTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("ThreadId");

                    b.HasIndex("OrganizationId", "ThreadId", "TagId")
                        .IsUnique();

                    b.ToTable("DiscussThreadTags", (string)null);
                });

            modelBuilder.Entity("Sellevate.Social.Features.Discuss.Models.DiscussVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "TargetType", "TargetId");

                    b.HasIndex("OrganizationId", "UserId", "TargetType", "TargetId")
                        .IsUnique();

                    b.ToTable("DiscussVotes", (string)null);
                });

            modelBuilder.Entity("Sellevate.Social.Features.Friends.Models.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanonicalHighId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasComputedColumnSql("GREATEST(\"RequesterId\", \"AddresseeId\")", true);

                    b.Property<Guid>("CanonicalLowId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid")
                        .HasComputedColumnSql("LEAST(\"RequesterId\", \"AddresseeId\")", true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "AddresseeId");

                    b.HasIndex("OrganizationId", "RequesterId");

                    b.HasIndex("OrganizationId", "CanonicalLowId", "CanonicalHighId")
                        .IsUnique()
                        .HasDatabaseName("IX_Friendships_CanonicalPair");

                    b.HasIndex("OrganizationId", "RequesterId", "AddresseeId")
                        .IsUnique();

                    b.ToTable("Friendships", null, t =>
                        {
                            t.HasCheckConstraint("CK_Friendships_NoSelfFriendship", "\"RequesterId\" != \"AddresseeId\"");
                        });
                });

            modelBuilder.Entity("Sellevate.Social.Identity.UserReplica", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarKey")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("UserReplicas", (string)null);
                });

            modelBuilder.Entity("Sellevate.Social.Features.Discuss.Models.DiscussReply", b =>
                {
                    b.HasOne("Sellevate.Social.Features.Discuss.Models.DiscussThread", "Thread")
                        .WithMany("Replies")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("Sellevate.Social.Features.Discuss.Models.DiscussThreadTag", b =>
                {
                    b.HasOne("Sellevate.Social.Features.Discuss.Models.DiscussTag", "Tag")
                        .WithMany("ThreadTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sellevate.Social.Features.Discuss.Models.DiscussThread", "Thread")
                        .WithMany("ThreadTags")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("Sellevate.Social.Features.Discuss.Models.DiscussTag", b =>
                {
                    b.Navigation("ThreadTags");
                });

            modelBuilder.Entity("Sellevate.Social.Features.Discuss.Models.DiscussThread", b =>
                {
                    b.Navigation("Replies");

                    b.Navigation("ThreadTags");
                });
#pragma warning restore 612, 618
        }
    }
}
